-- Create version table and set initial version mark
CREATE TABLE IF NOT EXISTS __theear_versions (version VARCHAR(255) NOT NULL, applied_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), PRIMARY KEY (version));
INSERT INTO __theear_versions (version) VALUES ('initial') ON CONFLICT (version) DO NOTHING;

-- Initialize tables for permissions and roles
CREATE TABLE IF NOT EXISTS auth_functional_permissions (perm_id UUID NOT NULL DEFAULT gen_random_uuid(), perm_name VARCHAR(255) NOT NULL, perm_action VARCHAR(255) NOT NULL DEFAULT '', perm_description TEXT NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), PRIMARY KEY(perm_id), UNIQUE(perm_name, perm_action));
CREATE TABLE IF NOT EXISTS auth_functional_permissions_on_java_element (perm_id UUID REFERENCES auth_functional_permissions(perm_id) ON DELETE CASCADE NOT NULL, type_name TEXT NOT NULL, operation_name TEXT NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), PRIMARY KEY (perm_id, type_name, operation_name));
CREATE TABLE IF NOT EXISTS auth_functional_permission_groups (perm_group_id UUID NOT NULL DEFAULT gen_random_uuid(), perm_group_name VARCHAR(255) NOT NULL, perm_group_description TEXT NOT NULL DEFAULT '', created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), PRIMARY KEY (perm_group_id, perm_group_name), UNIQUE (perm_group_id), UNIQUE (perm_group_name));
CREATE TABLE IF NOT EXISTS auth_functional_permission_groups_permissions (perm_group_id UUID REFERENCES auth_functional_permission_groups(perm_group_id) ON DELETE CASCADE NOT NULL, perm_id UUID REFERENCES auth_functional_permissions(perm_id) ON DELETE CASCADE NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), PRIMARY KEY (perm_group_id, perm_id));
CREATE TABLE IF NOT EXISTS auth_oidc_groups (oidc_issuer TEXT NOT NULL, oidc_group_name TEXT NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), PRIMARY KEY (oidc_issuer, oidc_group_name));
CREATE TABLE IF NOT EXISTS auth_functional_permission_group_oidc_group_map (perm_group_id UUID REFERENCES auth_functional_permission_groups(perm_group_id) ON DELETE CASCADE NOT NULL, oidc_issuer TEXT NOT NULL, oidc_group_name TEXT NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(), PRIMARY KEY (perm_group_id, oidc_issuer, oidc_group_name), FOREIGN KEY (oidc_issuer, oidc_group_name) REFERENCES auth_oidc_groups(oidc_issuer, oidc_group_name) ON DELETE CASCADE);
